// QR rendering for worker magic links (design doc §14, which committed to "magic links /
// QR codes generated by the administrator, per worker per event").
//
// Two constraints shape this module, and both come from the token being a live credential:
//
//  1. It is generated server-side and inlined into the response. The obvious alternative —
//     an `<img src="/api/qr?token=…">` endpoint — is exactly what actions.ts forbids: "a
//     token must never enter a URL". A token in an image URL lands in access logs, browser
//     history, and any Referer sent by the page.
//  2. It is rendered from the mint's return value, never from a re-read. Only the hash is
//     stored (src/workers.ts), so the plaintext exists for one render and the QR can only
//     be drawn in that same moment. There is deliberately no way to reprint one later;
//     rotating the link is how a worker who lost theirs gets another.
import QRCode from 'qrcode';

/**
 * Error correction level M — ~15% recoverable. Chosen over the L default because these are
 * scanned off a laptop screen in daylight, or off paper in a paddock, where a glare patch
 * or a thumbprint over one corner is the normal case rather than the exceptional one. H
 * would survive more damage but packs the modules tighter for the same payload, which is
 * the wrong trade for a phone camera at arm's length.
 */
const ERROR_CORRECTION = 'M' as const;

/**
 * Renders `text` as a standalone SVG QR code.
 *
 * SVG rather than a PNG data URI so it stays crisp at whatever size the manager's screen or
 * printer lands on — the payload is a URL of roughly 100 characters, which is dense enough
 * that resampling a fixed-resolution bitmap costs real scans.
 *
 * `margin: 2` is the smallest quiet zone that scanners reliably accept; the spec asks for 4
 * modules, but 2 plus the surrounding white card reads fine and keeps the code larger for a
 * given box. `width` fixes the SVG's intrinsic size so it does not collapse to zero height
 * in a flex container.
 */
export async function qrSvg(text: string): Promise<string> {
  return QRCode.toString(text, {
    type: 'svg',
    errorCorrectionLevel: ERROR_CORRECTION,
    margin: 2,
    width: 220,
  });
}
